# Generated by Django 5.2.9 on 2025-12-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_profile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="picture",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
